<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Company\Block\Company\Account\Create
 */
?>
<div class="registration-outer cms-container dealer">
<form class="form create account form-create-account"
      action="<?= /* @noEscape */ $block->getPostActionUrl() ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset info">
      <div class="companytype-outer">
        <legend class="legend">
          <span><?= $block->escapeHtml(__('TYPE OF COMPANY')) ?></span>
        </legend>
        <div class="field companytype">
         <label><input type="radio" name="company[customer_group_id]" checked class="dealercheck" value="4"><span class="cus-radio-btn"></span> <span>Dealer</span></label>
            <label><input type="radio" name="company[customer_group_id]" value="5"><span class="cus-radio-btn"></span> <span>Corporate</span></label>
             <label><input type="radio" name="company[customer_group_id]" value="6"><span class="cus-radio-btn"></span> <span>Employee</span></label>        
        </div>
      </div>
    </fieldset>
      <div class="company-frm-outer">
        <div class="company-frm">
           <fieldset class="fieldset create info">
          <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
            ->setObject($block->getFormData())
            ->setNoWrap(true)
            ->setForceUseCustomerAttributes(true)
            ->toHtml() ?>
         <div class="field telephone _required">
            <label class="label" for="telephone">
                <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[telephone]" id="telephone"
                       value=""
                       title="<?= $block->escapeHtml(__('Phone Number')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>

        <div class="field required">
            <label for="email_address" class="label"><span><?= /* @noEscape */ __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email"
                       autocomplete="email"
                       id="email_address"
                       value=""
                       title="<?= /* @noEscape */ __('Email') ?>"
                       class="input-text"
                       data-async-is-valid="true"
                       data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                            "name": "customer_email",
                            "validateUrl": "<?= /* @escapeNotVerified */ $block->getUrl('company/account/validate') ?>"
                       }}'
                       data-validate="{required:true, 'validate-email':true, 'validate-async-customer-email': true}">
            </div>
        </div>
          <div class="field password required"> 
           <label class="label" for="password">
                <span><?= $block->escapeHtml(__('Password')) ?></span>
            </label>                   
                    <div class="control">
                        <input type="password" name="password" id="password" title="Password" class="input-text"
                               data-password-min-length="8" data-password-min-character-sets="3"
                               data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off"
                               aria-required="true">                        
                    </div>
                </div>
                <div class="field confirmation required">
                   <label class="label" for="password-confirmation">
                      <span><?= $block->escapeHtml(__('Confirm Password')) ?></span>
                   </label>
                    <div class="control">
                        <input type="password" name="password_confirmation" title="Confirm Password"
                               id="password-confirmation" class="input-text"
                               data-validate="{required:true, equalTo:'#password'}" autocomplete="off"
                               aria-required="true">                          
                    </div>
                </div>
       
        <?php $gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?= $gender->setGender($block->getFormData()->getGender())->toHtml() ?>

        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
      </div>
        <div class="company-frm">
           <fieldset class="fieldset info">
       
       <div class="field company-name _required">
           <label class="label" for="company_name">
               <span><?= $block->escapeHtml(__('Organisation Name')) ?></span>
           </label>
           <div class="control">
               <input type="text" name="company[company_name]" id="company_name"
                      value=""
                      title="<?= $block->escapeHtml(__('Company Name')) ?>"
                      class="input-text" data-validate="{required:true}">
           </div>
       </div>
       
       <div class="field company-email _required">
           <label class="label" for="company_email">
               <span><?= $block->escapeHtml(__('Organisation Email')) ?></span>
           </label>
           <div class="control">
               <input type="email" name="company[company_email]" id="company_email"
                      value=""
                      title="<?= $block->escapeHtml(__('Company Email')) ?>"
                      class="input-text"
                      data-role="email"
                      data-async-is-valid="true"
                      data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                           "name": "company_email",
                           "validateUrl": "<?= /* @escapeNotVerified */ $block->getUrl('company/account/validate') ?>"
                      }}'
                      data-validate="{required:true, 'validate-email': true, 'validate-async-company-email': true}">
           </div>
       </div>
       
        <div class="field street _required">
            <label class="label" for="street0">
                <span><?= $block->escapeHtml(__('Dealer Address')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[street][0]" id="street0"
                       value=""
                       title="<?= $block->escapeHtml(__('Street Address')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field city _required">
            <label class="label" for="city">
                <span><?= $block->escapeHtml(__('City')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[city]" id="city"
                       value=""
                       title="<?= $block->escapeHtml(__('City')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>

         <div class="field street _required">
            <label class="label" for="street0">
                <span><?= $block->escapeHtml(__('Thane')) ?></span>
            </label>
        <div class="field street">
            <div class="control">
                <input type="text" name="company[street][1]" id="street1"
                       value=""
                       title="<?= $block->escapeHtml(__('Street Address')) ?>"
                       class="input-text">
            </div>
        </div>
      </div>
        
        <div class="field country_id _required">
            <label class="label" for="country_id">
                <span><?= $block->escapeHtml(__('Country')) ?></span>
            </label>
            <div class="control _required">
                <?php $countryValue = $block->getDefaultCountryId(); ?>
                <select name="company[country_id]" id="country_id"
                        class="select"
                        title="<?= $block->escapeHtml(__('Country')) ?>"
                        data-validate="{required:true}">
                    <option value=""></option>
                    <?php $countries = $block->getCountriesList(); ?>
                    <?php foreach($countries as $countryCode => $country): ?>
                        <option value="<?= $block->escapeHtml($countryCode) ?>"
                            <?= ($countryCode == $countryValue) ? ' selected' : '' ;?>>
                            <?= $block->escapeHtml($country) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="field region-id required">
            <label class="label" for="region_id">
                <span><?= $block->escapeHtml(__('State/Province')) ?></span>
            </label>
            <div class="control _required">
                <select name="company[region_id]" id="region_id" data-validate="{required:true}" class="select">
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="region" name="company[region]"
                       value=""
                       title="<?= $block->escapeHtml(__('State/Province')) ?>"
                       class="input-text" style="display: none;">
            </div>
        </div>
        <div class="field postcode required">
            <label class="label" for="postcode">
                <span><?= $block->escapeHtml(__('ZIP/Postal Code')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[postcode]" id="postcode"
                       value=""
                       title="<?= $block->escapeHtml(__('ZIP/Postal Code')) ?>"
                       class="input-text validate-zip-international <?= /* @escapeNotVerified */ $block->getAttributeValidationClass('postcode') ?>"
                       data-validate="{'required':true, 'validate-zip-international':true}" />
            </div>
        </div>

        
    </fieldset>
      </div>

        <div class="company-frm">
          <fieldset class="fieldset info">       
          <div class="field _required">
            <label class="label">
                <span><?= $block->escapeHtml(__('Security Question1')) ?></span>
            </label>
            <div class="control">
            <select name="security1" id="myselect" title="<?= $block->escapeHtml(__('Security Question1')) ?>" class="validate-select">
                <option disabled selected value> -- Please Select Security Questions -- </option>
                <option value="Which city you born?">Which city you born?</option>
                <option value="Who is your best friend?">Who is your best friend?</option>
            </select>
        </div>
      </div>
        <div class="field legal-name">
           <label class="label" for="">
               <span><?= $block->escapeHtml(__('Answer')) ?></span>
           </label>
           <div class="control">
               <input type="text" name="answer1" id="legal_name"
                      value=""
                      title="<?= $block->escapeHtml(__('Answer')) ?>"
                      class="input-text">
           </div>
       </div> 
       <div class="field _required">
            <label class="label">
                <span><?= $block->escapeHtml(__('Security Question2')) ?></span>
            </label>
          <div class="control">
            <select name="security2" id="myselect" title="<?= $block->escapeHtml(__('Security Question2')) ?>" class="validate-select">
                <option disabled selected value> -- Please Select Security Questions -- </option>
                <option value="What is your favourite color?">What is your favourite color?</option>
                <option value="What is your pet name?">What is your pet name?</option>
            </select>
        </div> 
      </div>
         <div class="field legal-name">
           <label class="label" for="">
               <span><?= $block->escapeHtml(__('Answer')) ?></span>
           </label>
           <div class="control">
               <input type="text" name="answer2" id="legal_name"
                      value=""
                      title="<?= $block->escapeHtml(__('Answer')) ?>"
                      class="input-text">
           </div>
       </div>
    </fieldset>
     </div>
      </div>
    
   <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtml(__('Submit')) ?>">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>

  </form>
</div>

<div class="registration-outer cms-container corporate">
<form class="form create account form-create-account"
      action="<?= /* @noEscape */ $block->getPostActionUrl() ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset info">
      <div class="companytype-outer">
        <legend class="legend">
          <span><?= $block->escapeHtml(__('TYPE OF COMPANY')) ?></span>
        </legend>
        <div class="field companytype">
         <label><input type="radio" name="company[customer_group_id]" value="4"><span class="cus-radio-btn"></span> <span>Dealer</span></label>
            <label><input type="radio" name="company[customer_group_id]" checked class="corporatecheck" value="5"><span class="cus-radio-btn"></span> <span>Corporate</span></label>
             <label><input type="radio" name="company[customer_group_id]" value="6"><span class="cus-radio-btn"></span> <span>Employee</span></label>        
        </div>
      </div>
    </fieldset>
      <div class="company-frm-outer">
        <div class="company-frm">
           <fieldset class="fieldset create info">
          <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
            ->setObject($block->getFormData())
            ->setNoWrap(true)
            ->setForceUseCustomerAttributes(true)
            ->toHtml() ?>
            <div class="field legal-name">
                <label class="label" for="job_title">
                    <span><?= $block->escapeHtml(__('Designation')) ?></span>
                </label>
                <div class="control">
                    <input type="text" name="job_title" id="job_title"
                           value=""
                           title="<?= $block->escapeHtml(__('Job Title')) ?>"
                           class="input-text">
                </div>
            </div>

        <div class="field required">
            <label for="email_address" class="label"><span><?= /* @noEscape */ __('Designated Employee Email Address') ?></span></label>
            <div class="control">
                <input type="email" name="email"
                       autocomplete="email"
                       id="email_address"
                       value=""
                       title="<?= /* @noEscape */ __('Email') ?>"
                       class="input-text"
                       data-async-is-valid="true"
                       data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                            "name": "customer_email",
                            "validateUrl": "<?= /* @escapeNotVerified */ $block->getUrl('company/account/validate') ?>"
                       }}'
                       data-validate="{required:true, 'validate-email':true, 'validate-async-customer-email': true}">
            </div>
        </div>

         <div class="field telephone _required">
            <label class="label" for="telephone">
                <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[telephone]" id="telephone"
                       value=""
                       title="<?= $block->escapeHtml(__('Phone Number')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>

          <div class="field password required"> 
           <label class="label" for="password">
                <span><?= $block->escapeHtml(__('Password')) ?></span>
            </label>                   
                    <div class="control">
                        <input type="password" name="password" id="password" title="Password" class="input-text"
                               data-password-min-length="8" data-password-min-character-sets="3"
                               data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off"
                               aria-required="true">                        
                    </div>
                </div>
                <div class="field confirmation required">
                   <label class="label" for="password-confirmation">
                      <span><?= $block->escapeHtml(__('Confirm Password')) ?></span>
                   </label>
                    <div class="control">
                        <input type="password" name="password_confirmation" title="Confirm Password"
                               id="password-confirmation" class="input-text"
                               data-validate="{required:true, equalTo:'#password'}" autocomplete="off"
                               aria-required="true">                          
                    </div>
                </div>
       
        <?php $gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?= $gender->setGender($block->getFormData()->getGender())->toHtml() ?>

        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
      </div>
        <div class="company-frm">
           <fieldset class="fieldset info">
       
       <div class="field company-name _required">
           <label class="label" for="company_name">
               <span><?= $block->escapeHtml(__('Organisation Name')) ?></span>
           </label>
           <div class="control">
               <input type="text" name="company[company_name]" id="company_name"
                      value=""
                      title="<?= $block->escapeHtml(__('Company Name')) ?>"
                      class="input-text" data-validate="{required:true}">
           </div>
       </div>
       
       <div class="field company-email _required">
           <label class="label" for="company_email">
               <span><?= $block->escapeHtml(__('Organisation Email')) ?></span>
           </label>
           <div class="control">
               <input type="email" name="company[company_email]" id="company_email"
                      value=""
                      title="<?= $block->escapeHtml(__('Company Email')) ?>"
                      class="input-text"
                      data-role="email"
                      data-async-is-valid="true"
                      data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                           "name": "company_email",
                           "validateUrl": "<?= /* @escapeNotVerified */ $block->getUrl('company/account/validate') ?>"
                      }}'
                      data-validate="{required:true, 'validate-email': true, 'validate-async-company-email': true}">
           </div>
       </div>
       
        <div class="field street _required">
            <label class="label" for="street0">
                <span><?= $block->escapeHtml(__('Organisation Address')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[street][0]" id="street0"
                       value=""
                       title="<?= $block->escapeHtml(__('Street Address')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field city _required">
            <label class="label" for="city">
                <span><?= $block->escapeHtml(__('City')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[city]" id="city"
                       value=""
                       title="<?= $block->escapeHtml(__('City')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>

         <div class="field street _required">
            <label class="label" for="street0">
                <span><?= $block->escapeHtml(__('Thane')) ?></span>
            </label>
        <div class="field street">
            <div class="control">
                <input type="text" name="company[street][1]" id="street1"
                       value=""
                       title="<?= $block->escapeHtml(__('Street Address')) ?>"
                       class="input-text">
            </div>
        </div>
      </div>
        
        <div class="field country_id _required">
            <label class="label" for="country_id">
                <span><?= $block->escapeHtml(__('Country')) ?></span>
            </label>
            <div class="control _required">
                <?php $countryValue = $block->getDefaultCountryId(); ?>
                <select name="company[country_id]" id="country_id"
                        class="select"
                        title="<?= $block->escapeHtml(__('Country')) ?>"
                        data-validate="{required:true}">
                    <option value=""></option>
                    <?php $countries = $block->getCountriesList(); ?>
                    <?php foreach($countries as $countryCode => $country): ?>
                        <option value="<?= $block->escapeHtml($countryCode) ?>"
                            <?= ($countryCode == $countryValue) ? ' selected' : '' ;?>>
                            <?= $block->escapeHtml($country) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div class="field region-id required">
            <label class="label" for="region_id">
                <span><?= $block->escapeHtml(__('State/Province')) ?></span>
            </label>
            <div class="control _required">
                <select name="company[region_id]" id="region_id" data-validate="{required:true}" class="select">
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="region" name="company[region]"
                       value=""
                       title="<?= $block->escapeHtml(__('State/Province')) ?>"
                       class="input-text" style="display: none;">
            </div>
        </div>
        <div class="field postcode required">
            <label class="label" for="postcode">
                <span><?= $block->escapeHtml(__('ZIP/Postal Code')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[postcode]" id="postcode"
                       value=""
                       title="<?= $block->escapeHtml(__('ZIP/Postal Code')) ?>"
                       class="input-text validate-zip-international <?= /* @escapeNotVerified */ $block->getAttributeValidationClass('postcode') ?>"
                       data-validate="{'required':true, 'validate-zip-international':true}" />
            </div>
        </div>

        
    </fieldset>
      </div>

        <div class="company-frm">
          <fieldset class="fieldset info">      
           <div class="field _required">
            <label class="label">
                <span><?= $block->escapeHtml(__('Security Question1')) ?></span>
            </label>
            <div class="control">
            <select name="security1" id="myselect" title="<?= $block->escapeHtml(__('Security Question1')) ?>" class="validate-select">
                <option disabled selected value> -- Please Select Security Questions -- </option>
                <option value="Which city you born?">Which city you born?</option>
                <option value="Who is your best friend?">Who is your best friend?</option>
            </select>
        </div>
      </div>
        <div class="field legal-name">
           <label class="label" for="">
               <span><?= $block->escapeHtml(__('Answer')) ?></span>
           </label>
           <div class="control">
               <input type="text" name="answer1" id="legal_name"
                      value=""
                      title="<?= $block->escapeHtml(__('Answer')) ?>"
                      class="input-text">
           </div>
       </div> 
       <div class="field _required">
            <label class="label">
                <span><?= $block->escapeHtml(__('Security Question2')) ?></span>
            </label>
          <div class="control">
            <select name="security2" id="myselect" title="<?= $block->escapeHtml(__('Security Question2')) ?>" class="validate-select">
                <option disabled selected value> -- Please Select Security Questions -- </option>
                <option value="What is your favourite color?">What is your favourite color?</option>
                <option value="What is your pet name?">What is your pet name?</option>
            </select>
        </div> 
      </div>
         <div class="field legal-name">
           <label class="label" for="">
               <span><?= $block->escapeHtml(__('Answer')) ?></span>
           </label>
           <div class="control">
               <input type="text" name="answer2" id="legal_name"
                      value=""
                      title="<?= $block->escapeHtml(__('Answer')) ?>"
                      class="input-text">
           </div>
       </div>
    </fieldset>
     </div>
      

      </div>
    
   <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtml(__('Submit')) ?>">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>

  </form>
</div>   


<div class="registration-outer cms-container employee">
<form class="form create account form-create-account"
      action="<?= /* @noEscape */ $block->getPostActionUrl() ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <?= $block->getBlockHtml('formkey') ?>
    <?= $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset info">
      <div class="companytype-outer">
        <legend class="legend">
          <span><?= $block->escapeHtml(__('TYPE OF COMPANY')) ?></span>
        </legend>
        <div class="field companytype">
         <label><input type="radio" name="company[customer_group_id]" value="4"><span class="cus-radio-btn"></span> <span>Dealer</span></label>
            <label><input type="radio" name="company[customer_group_id]" value="5"><span class="cus-radio-btn"></span> <span>Corporate</span></label>
             <label><input type="radio" name="company[customer_group_id]" class="employeecheck" checked value="6"><span class="cus-radio-btn"></span> <span>Employee</span></label>        
        </div>
      </div>
    </fieldset>
      <div class="company-frm-outer">
        <div class="company-frm">
           <fieldset class="fieldset create info account">
          <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
            ->setObject($block->getFormData())
            ->setNoWrap(true)
            ->setForceUseCustomerAttributes(true)
            ->toHtml() ?>
         <div class="field telephone _required">
            <label class="label" for="telephone">
                <span><?= $block->escapeHtml(__('Phone Number')) ?></span>
            </label>
            <div class="control">
                <input type="text" name="company[telephone]" id="telephone"
                       value=""
                       title="<?= $block->escapeHtml(__('Phone Number')) ?>"
                       class="input-text" data-validate="{required:true}">
            </div>
        </div>

        <div class="field required">
            <label for="email_address" class="label"><span><?= /* @noEscape */ __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email"
                       autocomplete="email"
                       id="email_address"
                       value=""
                       title="<?= /* @noEscape */ __('Email') ?>"
                       class="input-text"
                       data-async-is-valid="true"
                       data-mage-init='{"Magento_Company/js/form/element/async-validation": {
                            "name": "customer_email",
                            "validateUrl": "<?= /* @escapeNotVerified */ $block->getUrl('company/account/validate') ?>"
                       }}'
                       data-validate="{required:true, 'validate-email':true, 'validate-async-customer-email': true}">
            </div>
        </div>
          <div class="field password required"> 
           <label class="label" for="password">
                <span><?= $block->escapeHtml(__('Password')) ?></span>
            </label>                   
                    <div class="control">
                        <input type="password" name="password" id="password" title="Password" class="input-text"
                               data-password-min-length="8" data-password-min-character-sets="3"
                               data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off"
                               aria-required="true">                        
                    </div>
                </div>
                <div class="field confirmation required">
                   <label class="label" for="password-confirmation">
                      <span><?= $block->escapeHtml(__('Confirm Password')) ?></span>
                   </label>
                    <div class="control">
                        <input type="password" name="password_confirmation" title="Confirm Password"
                               id="password-confirmation" class="input-text"
                               data-validate="{required:true, equalTo:'#password'}" autocomplete="off"
                               aria-required="true">                          
                    </div>
                </div>
       
        <?php $gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?= $gender->setGender($block->getFormData()->getGender())->toHtml() ?>

        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
      </div>
       <div class="company-frm">
          <fieldset class="fieldset info">      
        <div class="field _required">
            <label class="label">
                <span><?= $block->escapeHtml(__('Security Question1')) ?></span>
            </label>
            <div class="control">
            <select name="security1" id="myselect" title="<?= $block->escapeHtml(__('Security Question1')) ?>" class="validate-select">
                <option disabled selected value> -- Please Select Security Questions -- </option>
                <option value="Which city you born?">Which city you born?</option>
                <option value="Who is your best friend?">Who is your best friend?</option>
            </select>
        </div>
      </div>
        <div class="field legal-name">
           <label class="label" for="">
               <span><?= $block->escapeHtml(__('Answer')) ?></span>
           </label>
           <div class="control">
               <input type="text" name="answer1" id="legal_name"
                      value=""
                      title="<?= $block->escapeHtml(__('Answer')) ?>"
                      class="input-text">
           </div>
       </div> 
       <div class="field _required">
            <label class="label">
                <span><?= $block->escapeHtml(__('Security Question2')) ?></span>
            </label>
          <div class="control">
            <select name="security2" id="myselect" title="<?= $block->escapeHtml(__('Security Question2')) ?>" class="validate-select">
                <option disabled selected value> -- Please Select Security Questions -- </option>
                <option value="What is your favourite color?">What is your favourite color?</option>
                <option value="What is your pet name?">What is your pet name?</option>
            </select>
        </div> 
      </div>
         <div class="field legal-name">
           <label class="label" for="">
               <span><?= $block->escapeHtml(__('Answer')) ?></span>
           </label>
           <div class="control">
               <input type="text" name="answer2" id="legal_name"
                      value=""
                      title="<?= $block->escapeHtml(__('Answer')) ?>"
                      class="input-text">
           </div>
       </div>
    </fieldset>
     </div>
      </div>
    
   <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $block->escapeHtml(__('Submit')) ?>">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>

  </form>
</div>

<script>
    require([
        'jquery',
        'mage/mage'
    ], function($) {

        var dataForm = $('#form-validate');
        var ignore = null;

        dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');

         $(".corporate").hide();
         $(".employee").hide();

        $("input[type='radio']").click(function(){
            if($(this).val()=="5")
           {  
              $(".dealer").hide();
              $(".employee").hide();
              $(".corporate").show();
              $(".corporatecheck").prop("checked",true);
           }
           else if($(this).val()=="6")
           {   
               $(".dealer").hide();
               $(".corporate").hide(); 
               $(".employee").show();
               $(".employeecheck").prop("checked",true);
           }
           else{
            if($(this).val()=="4")
               { 
                $(".corporate").hide();
                $(".employee").hide();
                $(".dealer").show();
                $(".dealercheck").prop("checked",true);
              }
           }

        });
    });
    
</script>
<script type="text/x-magento-init">
    {
        "#country_id": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>

