<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
?>

<?php $total = $block->getItems()->getSize() ?>
<?php if ($total): ?>
   <div class="com-print-right fixed-com-print">

                    <a class="action email" href="mailto:$email?body=$fixed_body">EMAIL</a>
                    <a class="action print" href="#">PRINT</a>
    </div>
        <div class="table-wrapper comparison">
            <table class="data table table-comparison" id="product-comparison"
                data-mage-init='{"compareList":{
                    "windowPrintSelector":".action.print",
                    "productsInRow":"5",
                    "selectors":{
                        "productAddToCartSelector":"button.action.tocart"}
                }}' cellspacing="0" cellpadding="0">
               
                <thead>
                <tr>
                    <?php $index = 0 ?>
                    <?php foreach ($block->getItems() as $item): ?>
                        <?php if ($index++ == 0): ?>
                            <th scope="row" class="cell label remove"><span><?= /* @escapeNotVerified */ __('Remove Product') ?></span></th>
                        <?php endif; ?>
                        <td class="cell remove product hidden-print">
                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                            <a href="#" data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataRemove($item) ?>'
                               class="action delete" title="<?= /* @escapeNotVerified */ __('Remove Product') ?>">
                                <span><?= /* @escapeNotVerified */ __('Remove Product') ?></span>
                            </a>
                        </td>
                    <?php endforeach; ?>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <?php $index = 0; ?>
                    <?php $helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
                    <?php /** @var $item \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($block->getItems() as $item): ?>
                        <?php if ($index++ == 0): ?>
                            <th scope="row" class="cell label product"><span></span></th>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Product')) ?>" class="cell product info">
                             <div class="remove product">
                                 <a href="#" data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataRemove($item) ?>'
                               class="action delete" title="<?= /* @escapeNotVerified */ __('Remove Product') ?>">
                                <span><?= /* @escapeNotVerified */ __('Remove Product') ?></span>
                                 </a>
                             </div>
                             <div class="product-info-outer">
                            <a class="product-item-photo" href="<?= /* @escapeNotVerified */ $block->getProductUrl($item) ?>" title="<?= /* @escapeNotVerified */ $block->stripTags($item->getName(), null, true) ?>">
                                <?= $block->getImage($item, 'product_comparison_list')->toHtml() ?>
                            </a>
                            <strong class="product-item-name">
                                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($item) ?>" title="<?= /* @escapeNotVerified */ $block->stripTags($item->getName(), null, true) ?>">
                                    <?= /* @escapeNotVerified */ $helper->productAttribute($item, $item->getName(), 'name') ?>
                                </a>
                            </strong>
                            <div class="rating">
                                                        <span class="fa fa-star checked"></span>
                                                        <span class="fa fa-star checked"></span>
                                                        <span class="fa fa-star checked"></span>
                                                        <span class="fa fa-star"></span>
                                                        <span class="fa fa-star"></span>
                             </div>
                              <?= $block->getReviewsSummaryHtml($item, 'short') ?>
                          

                            <?= /* @escapeNotVerified */ $block->getProductPrice($item, '-compare-list-top') ?>
                            <div class="product-item-actions hidden-print">
                                <div class="actions-primary">
                                    <?php if ($item->isSaleable()): ?>
                                        <form data-role="tocart-form" action="<?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($item) ?>" method="post">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit" class="action tocart primary1">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($item->getIsSalable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                        <a href="#" data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($item) ?>' class="action towishlist" data-action="add-to-wishlist">
                                            <span><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
                                        </a>
                                    </div>
                                <?php endif; ?>
                            </div>
                           </div> 
                        </td>
                    <?php endforeach; ?>
                </tr>
                </tbody>
                <tbody>
                                <tr>
                                    <td colspan="4">
                                        <section class="compare-item-info mode-differences">
                                            <div class="compare-title-outer">
                                                <h2>Technical Specifications</h2>
                                                <div class="choice-control-outer">
                                                    <dl class="choice-control">
                                                        <dt>Show:</dt>
                                                        <dd class="all"><a href="#">All</a></dd>
                                                        <dd class="clicked"><a href="#">Differences</a></dd>
                                                        <dd class="disabled">
                                                            <a href="#">Selection</a>
                                                            <a class="icon" href="#">!</a>
                                                        </dd>
                                                    </dl>
                                                </div>
                                            </div>
                                            <div class="collaps-all-outre">
                                                <span class="collaps-all">Collapse All</span>
                                            </div>
                                        </section>
                                    </td>
                                </tr>
                  </tbody>
                <tbody>
                <?php foreach ($block->getAttributes() as $attribute): ?>
                    <?php $index = 0; ?>
                    <?php if ($block->hasAttributeValueForProducts($attribute)): ?>
                         <tr>
                            <?php foreach ($block->getItems() as $item): ?>
                                <?php if ($index++ == 0): ?>
                                    <th scope="row" class="cell label">
                                        <span class="attribute label">
                                            <?= $block->escapeHtml($attribute->getStoreLabel() ? $attribute->getStoreLabel() : __($attribute->getFrontendLabel())) ?>
                                        </span>
                                    </th>
                                <?php endif; ?>
                                <td class="cell product attribute">
                                    <div class="attribute value">
                                        <?php switch ($attribute->getAttributeCode()) {
                                            case "price": ?>
                                                <?php
                                                    /* @escapeNotVerified */ echo $block->getProductPrice(
                                                        $item,
                                                        '-compare-list-' . $attribute->getCode()
                                                    )
                                                ?>
                                                <?php break;
                                            case "small_image": ?>
                                                <?php $block->getImage($item, 'product_small_image')->toHtml(); ?>
                                                <?php break;
                                            default: ?>
                                                <?php if (is_string($block->getProductAttributeValue($item, $attribute))): ?>
                                                    <?= /* @escapeNotVerified */ $helper->productAttribute($item, $block->getProductAttributeValue($item, $attribute), $attribute->getAttributeCode()) ?>
                                                <?php endif; ?>
                                            <?php break;
                                        } ?>
                                    </div>
                                </td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
                </tbody>
                
                    <tbody class="pro-details-outer">
                                <tr class="info-technical-outer">
                                    <td colspan="4" class="catagory-main">
                                        <div class="compare-item-info-outer">
                                            <table class="compare-pro-details" cellspacing="0" cellpadding="0" style="width:100%;">
                                                <tbody>
                                                    <tr class="catagory-main-title-outer">
                                                        <td>
                                                            <div class="catagory-main-title">
                                                                TVs
                                                            </div>
                                                        </td>
                                                    </tr>
                                                    <tr class="sub-catagory-outer">
                                                        <td class="sub-catagory">
                                                            <table class="compare-pro-sub" cellspacing="0" cellpadding="0" style="width:100%;">
                                                                <tr>
                                                                    <td class="sub-catagory-title-outer" colspan="4">
                                                                        <div class="sub-catagory-title">ACCESSORIES INCLUDED</div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">Power Cable</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">Remote Control Battery</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">Remote</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">User Manual</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">E- Manual</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">Quick Start Guide</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                    <tr class="sub-catagory-outer">
                                                        <td class="sub-catagory">
                                                            <table class="compare-pro-sub" cellspacing="0" cellpadding="0" style="width:100%;">
                                                                <tr>
                                                                    <td class="sub-catagory-title-outer" colspan="4">
                                                                        <div class="sub-catagory-title">AUDIO</div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">Bluetooth Audio Play</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">back</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">Output Power  </span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">LG Sound Sync</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">DTS Decoder</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">Dolby Atmos®</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                                <tr class="pro-attribute-outer">
                                                                    <th class="cell label">
                                                                        <div class="attribute-outer margin-left">
                                                                            <ul>
                                                                                <li>
                                                                                    <input type="checkbox" name="" value=""/>
                                                                                    <span class="attribute label">Speaker System</span>
                                                                                </li>
                                                                                
                                                                            </ul>
                                                                        </div>
                                                                    </th>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute">
                                                                        <div class="attribute value">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                    <td class="cell product attribute ">
                                                                        <div class="attribute value margin-right">
                                                                            yes
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>


            </table>
        </div>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            </script>
        <?php endif; ?>
<?php else: ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('You have no items to compare.') ?></div></div>
<?php endif; ?>




<script>
jQuery(document).ready(function(){
  jQuery(".collaps-all").click(function(){
    jQuery(".sub-catagory-outer").toggle();
  });
  jQuery(".catagory-main-title").click(function(){
    jQuery(".sub-catagory-outer").toggle();
    jQuery(this).toggleClass("arrow-open");
  });
  
  jQuery(".arrow").click(function(){
    jQuery(".action-calculator-body").toggleClass("calculator-full");
  });
  
});

jQuery('body').on('click','.sub-catagory-title',function(){

    jQuery(this).closest('table').toggleClass('hidden-area');

})

jQuery(window).scroll(function() {    
    var scroll = jQuery(window).scrollTop();

     //>=, not <=
    if (scroll >= 300) {
        //clearHeader, not clearheader - caps H
        jQuery(".compare-pro-list").addClass("com-fixed");
        jQuery(".fixed-com-print").addClass("com-fixed");
        jQuery(".compare-item-info").addClass("com-fixed");
    }else if(scroll < 300) {
        //clearHeader, not clearheader - caps H
        jQuery(".compare-pro-list").removeClass("com-fixed");
        jQuery(".fixed-com-print").removeClass("com-fixed");
        jQuery(".compare-item-info").removeClass("com-fixed");
    }
}); //missing );

</script>


