<?php
/**
 * @copyright Copyright (c) 2017 www.tigren.com
 * @var $block \Tigren\Ajaxlogin\Block\Form\Login
 */
?>
<div class="mb-login-popup" style="display:none;">
  <div class="container register butterfly-home-registration">               
                       <div class="butterfly-signup" >
    <div class="mb-ajaxsuite-popup-border mb-ajaxlogin-popup mb-ajaxlogin-login">
     
        <div class="block block-customer-login">
           <!--  <div class="block-title">
                <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Account Login')) ?></strong>
            </div> -->
            <div class="home-cus-sign-in-title">                  
                     <h3 class="home-customer-title">Already Have An Account</h3>                  
                     <h4 class="home-customer-small-head">Sign In To Track Your Order, Use Wishlist & More. </h4>         
                  </div>
            <form class="form butterfly-signup-form"
                  method="post"
                  id="ajax-login-form"
                  enctype="multipart/form-data" autocomplete="off">
              <?php echo $block->getBlockHtml('formkey'); ?>
                <div class="login" data-hasrequired="<?php echo __('* Required Fields') ?>">
                    <div class="email required but-home-login">
                        <label class="label" for="email"><span><?php echo __('Enter Your Email') ?></span></label>
                        <div class="control form-group">
                            <input name="login[username]"
                                   value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
                                   id="ajaxlogin-email" type="email" class="input-text" title="<?php echo __('Email') ?>"
                                   data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <div class="password required but-home-login">
                        <label for="pass" class="label"><span><?php echo __('Enter Your Password') ?></span></label>
                        <div class="control form-group">
                            <input name="login[password]"
                                   type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
                                   class="input-text" id="ajaxlogin-pass signin-password" title="<?php echo __('Password') ?>"
                                   data-validate="{required:true, 'validate-password':true}">
                        </div>
                    </div>
                </div>
                <div class="butter-home-login-remember">                      
                      <input type="radio" name="" value="" required>
                      <input class="form-check-input css-checkbox" type="checkbox" id="keep-me" value="" required>                       
                      <label for="keep-me">Keep Me Signed In</label>                      
                  </div>
                 
                        <button type="submit" class="action submit primary btn btn-block waves-effect z-depth-0 btn-sign-in" name="login" id="login">
                           <?php echo __('SIGN IN') ?>
                        </button>
                 
              <?php if ($block->isEnableSocialLogin() && !$block->isLoggedIn()): ?>
                  <div id="social-login">
                      <div class="primary">
                        <?php if ($this->helper('Tigren\Ajaxlogin\Helper\Data')->getScopeConfig('ajaxlogin/social_login/facebook_appid')) { ?>
                            <button id="facebook-login-btn" type="button" class="action social-login-btn primary">
                                <span><?php echo __('Facebook Login') ?></span>
                            </button>
                        <?php } ?>
                        <?php if ($this->helper('Tigren\Ajaxlogin\Helper\Data')->getScopeConfig('ajaxlogin/social_login/googleplus_clientid')) { ?>
                            <button id="ggplus-login-btn" type="button" class="action social-login-btn primary">
                                <span><?php echo __('Google+ Login') ?></span>
                            </button>
                        <?php } ?>
                        <?php if ($this->helper('Tigren\Ajaxlogin\Helper\Data')->getScopeConfig('ajaxlogin/social_login/twitter_consumer_key')
                          && $this->helper('Tigren\Ajaxlogin\Helper\Data')->getScopeConfig('ajaxlogin/social_login/twitter_consumer_secret')
                        ) {
                          ?>
                            <button id="twitter-login-btn" type="button" class="action social-login-btn primary">
                                <span><?php echo __('Twitter Login') ?></span>
                            </button>
                        <?php } ?>
                      </div>
                  </div>
              <?php endif; ?>
                
                    <div class="secondary forgt-pass">
                        <a class="action forgot" href="<?php echo $block->getForgotPasswordUrl() ?>">
                            <span><?php echo __('Forgot Your Password?') ?></span>
                        </a>
                    </div>
               
            </form>
            
                    <div class="cus-home-reg">
                        <a href="<?php echo $block->getUrl('customer/account/create'); ?>">
                          <span class="cus-home-reg-not-yet-member" id="Reg-now"><?= $block->escapeHtml(__('Not a member yet ? Sign Up Now')) ?></span></a>
                    </div>
                
        </div>       
      </div>
    </div>
    </div>
</div>