<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                <div class="product photo product-item-photo">
                           
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>

                    <a  href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"  tabindex="-1">
                        
                         <?= $productImage->toHtml() ?>
                    
                    </a> 

                    

                        </div>
                    <div class="product details product-item-details">
                        <div class="size">
                        <?= $block->getProductDetailsHtml($_product) ?>
                        </div>

                       
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                         
                       <!-- <div class="product name product-item-name">                       
                            <h2>  <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a></h2> 
                         </div> -->
                         
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                            </strong>

                        <div class="rating checked">
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        </div>
                        <div class="price"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></div>
                        </div>
                        <div class="how-buy">
                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary product-list-add-to-cart">
                                                <span class="how-buy"><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                        </div>
                            <div class="desk-compare-outer">
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="mob-cart-outer">
                            <button class="action tocart primary btn--ys">
                                <span>ADD TO CART</span>
                            </button>
                            <a class="add-to-compare" href="#">ADD TO COMPARE</a>
                        </div>
                        <a href="#" class="action todowishlist"><i class="fa">&#xf08a;</i></i></a>
                    
                    </div>

                </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<form id="ajaxactons" method="POST" name="ajaxactons"
     data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
     data-mage-init='{"validation":{}}'>
<div class="action-calculator-outer">
        <div class="action-calculator-title">
            <span class="arrow">></span>
            <span class="arrow-close">X</span>          
            <span class="con">AC TON CALCULATOR</span>
        </div>
        <div class="action-calculator-body">            
            <div class="title">
                <h2>AC TON CALCULATOR</h2>
            </div>
            <div class="action-calculator-from">
                <ul>
                    <li class="size">
                        <label>Size (ft)*:</label>
                        <div>
                            <input class="input-text" id="length" type="text" name="length" placeholder="Length" data-validate="{required:true, 'pattern':/^\d+(\.\d{1,2})?$/, 'validate-greater-than-zero':true}"/>
                            <input class="input-text" type="text" name="breadth" id="breadth" placeholder="Breadth"
                            data-validate="{required:true, 'pattern':/^\d+(\.\d{1,2})?$/, 'validate-greater-than-zero':true}"/>
                        </div>
                    </li>
                    <li class="type">
                        <label>House Age*:</label>
                        <div>
                            <select class="validate-select" name="houseage" id="houseage">
                                <option  value="" selected>--Select--</option>
                                <option  value="Old">Old</option> 
                                <option  value="new">New</option>                           
                            </select>
                        </div>
                    </li>
                    
                    <li class="cli">
                        <label>Climate*:</label>
                        <div>
                            <select class="validate-select" name="climate" id="climate" >
                                <option value="" selected>--Select--</option> 
                                <option value="Warm" >Warm</option> 
                                <option value="Cold">Cold</option>                          
                            </select>
                        </div>
                    </li>
                    
                </ul>
                <ul>
                    <li class="room-cel">
                        <label>Room Ceiling Height (ft)*:</label>
                        <div>
                            <input class="input-text" name="height" id="height" type="text" placeholder="Height"
                             data-validate="{required:true, 'pattern':/^\d+(\.\d{1,2})?$/, 'validate-greater-than-zero':true}"
                            />                          
                        </div>
                    </li>
                    <li class="ins">
                        <label>Insulation Condition*:</label>
                        <div>
                            <select class="validate-select" name="insulation" id="insulation">
                                <option value="" selected>-- Select --</option>                             
                                <option value="Poor">Poor</option> 
                                <option value="good">Good</option>                          
                            </select>
                        </div>
                    </li>
                    
                </ul>
                <ul class="number-people">
                    <li class="number">
                        <label>Number of People*:</label>
                        <input class="input-text" name="noofpeople"  id="noofpeople" type="text"
                        data-validate="{required:true, 'pattern':/^\d+(\.\d{1,2})?$/, 'integer':true}"
                        />
                    </li>
                    <li class="cal-button">
                        <input type="button" id="calculateTotalSubmit"  name="calculate-total-submit" value="Calculate"/>
                        <input type="reset" value="clear" class="acclear"/> 
                    </li>
                </ul>  
           
                <ul class="calculator-result">              
                    <li class="result">
                        <label>Recommended Tonnage:</label>
                        <div id="resul" class="recommended-result"></div>
                        <div id="load" style="display: none" class="loader"></div>  
                    </li>       
                </ul>

            </div>
        </div>
    </div>
</form> 


<?php 
$ajaxurl =  $block->getBaseUrl(). '/actn/actonform/index';
?>

<script type="text/javascript">
    require(
        [
            'jquery'
        ],
        function($,modal){
            jQuery("#calculateTotalSubmit").click(function(){
                var length = $("#length").val();
                var breadth = $("#breadth").val();
                var houseage = $("#houseage").val();
                var climate = $("#climate").val();
                var height = $("#height").val();
                var insulation = $("#insulation").val();
                var noofpeople = $("#noofpeople").val();
            jQuery("#load").css("display", "block"); 

            jQuery.ajax({        
                        url: "<?php echo $ajaxurl; ?>",
                        type: 'POST',
                        dataType: 'json',
                        data: {
                            "length": length,
                            "breadth": breadth,
                            "houseage": houseage,
                            "climate": climate,
                            "height": height,
                            "insulation": insulation,
                            "noofpeople": noofpeople,
                        },

                         success: function (res){
                          console.log(res);
                          jQuery("#resul").html(res); 
                          jQuery("#load").css("display", "none");
                         }
              
                       });

            }); 

        });
</script>


<style>
.loader {
    float: right;
    border: 7px solid #f3f3f3;
    border-radius: 50%;
    border-top: 7px solid #3498db;
    width: 14px;
    height: 14px;
    -webkit-animation: spin 2s linear infinite;
    animation: spin 2s linear infinite;
}
  
  /* Safari */
  @-webkit-keyframes spin {
    0% { -webkit-transform: rotate(0deg); }
    100% { -webkit-transform: rotate(360deg); }
  }
  
  @keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
  }
  .rating-summary .rating-result > span:before {
    
    color: #a40033 !important;

}


.swatch-attribute.size .swatch-option, .swatch-attribute.manufacturer .swatch-option {
    background: #ffffff;
    color: #070707;
}


 .swatch-attribute-options {
    margin-top: 10px;
    display: inline-block;
    text-align: center;
    vertical-align: top;
    height: 24px;
    line-height: 24px;
    margin-left: 5px;
}

.bundle-options-container .block-bundle-summary .product-addto-links > .action, .product-item-actions .actions-secondary > .action, .product-social-links .action.tocompare, .wishlist.split.button > .action.split, .product-social-links .action.mailto.friend, .product-social-links .action.towishlist, .block-bundle-summary .action.towishlist, .product-item .action.towishlist, .table-comparison .action.towishlist {
    color: #666666;
    font-weight: 600;
    letter-spacing: .05em;
    text-transform: uppercase;
    display: none !important;
    text-decoration: none;
}


</style>


