<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>

                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <?= $block->getProductDetailsHtml($_product) ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <div class="rating">
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                        </div>
                        <?= /* @escapeNotVerified */ $block->getProductName($_product) ?>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description lern-more">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                           
                       
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<form id="ajaxactons" method="POST" name="ajaxactons"
     data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
     data-mage-init='{"validation":{}}'>
<div class="action-calculator-outer">
        <div class="action-calculator-title">
            <span class="arrow">></span>
            <span class="arrow-close">X</span>          
            <span class="con">AC TON CALCULATOR</span>
        </div>
        <div class="action-calculator-body">            
            <div class="title">
                <h2>AC TON CALCULATOR</h2>
            </div>
            <div class="action-calculator-from">
                <ul>
                    <li class="size">
                        <label>Size (ft)*:</label>
                        <div>
                            <input class="input-text" id="length" type="text" name="length" placeholder="Length" data-validate="{required:true, 'pattern':/^\d+(\.\d{1,2})?$/, 'validate-greater-than-zero':true}"/>
                            <input class="input-text" type="text" name="breadth" id="breadth" placeholder="Breadth"
                            data-validate="{required:true, 'pattern':/^\d+(\.\d{1,2})?$/, 'validate-greater-than-zero':true}"/>
                        </div>
                    </li>
                    <li class="type">
                        <label>House Age*:</label>
                        <div>
                            <select class="validate-select" name="houseage" id="houseage">
                                <option  value="" selected>--Select--</option>
                                <option  value="Old">Old</option> 
                                <option  value="new">New</option>                           
                            </select>
                        </div>
                    </li>
                    
                    <li class="cli">
                        <label>Climate*:</label>
                        <div>
                            <select class="validate-select" name="climate" id="climate" >
                                <option value="" selected>--Select--</option> 
                                <option value="Warm" >Warm</option> 
                                <option value="Cold">Cold</option>                          
                            </select>
                        </div>
                    </li>
                    
                </ul>
                <ul>
                    <li class="room-cel">
                        <label>Room Ceiling Height (ft)*:</label>
                        <div>
                            <input class="input-text" name="height" id="height" type="text" placeholder="Height"
                             data-validate="{required:true, 'pattern':/^\d+(\.\d{1,2})?$/, 'validate-greater-than-zero':true}"
                            />                          
                        </div>
                    </li>
                    <li class="ins">
                        <label>Insulation Condition*:</label>
                        <div>
                            <select class="validate-select" name="insulation" id="insulation">
                                <option value="" selected>-- Select --</option>                             
                                <option value="Poor">Poor</option> 
                                <option value="good">Good</option>                          
                            </select>
                        </div>
                    </li>
                    
                </ul>
                <ul class="number-people">
                    <li class="number">
                        <label>Number of People*:</label>
                        <input class="input-text" name="noofpeople"  id="noofpeople" type="text"
                        data-validate="{required:true, 'pattern':/^\d+(\.\d{1,2})?$/, 'integer':true}"
                        />
                    </li>
                    <li class="cal-button">
                        <input type="button" id="calculateTotalSubmit"  name="calculate-total-submit" value="Calculate Total">
                    </li>
                </ul>               
                <ul class="calculator-result">              
                    <li class="result">
                        <label>Recommended Tonnage:</label>
                        <div id="resul" class="recommended-result"></div>
                    </li>       
                </ul>
            </div>
        </div>
    </div>
</form> 


<?php 
$ajaxurl = 'http://localhost/butterflygit/actn/actonform/index';
?>

<script type="text/javascript">
    require(
        [
            'jquery'
        ],
        function($,modal){
            jQuery("#calculateTotalSubmit").click(function(){
                var length = $("#length").val();
                var breadth = $("#breadth").val();
                var houseage = $("#houseage").val();
                var climate = $("#climate").val();
                var height = $("#height").val();
                var insulation = $("#insulation").val();
                var noofpeople = $("#noofpeople").val();
            
            jQuery.ajax({        
                        url: "<?php echo $ajaxurl; ?>",
                        type: 'POST',
                        dataType: 'json',
                        data: {
                            "length": length,
                            "breadth": breadth,
                            "houseage": houseage,
                            "climate": climate,
                            "height": height,
                            "insulation": insulation,
                            "noofpeople": noofpeople,
                        },
                         success: function (res){
                            console.log(res);
                           jQuery("#resul").html(res); 
                         }
              
                       });

            }); 

        });
</script>





