<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$catId = $objectManager->create('Magento\Catalog\Model\Category')->getCollection()
->addFieldToFilter('name','offer')
->setPageSize(1);
if($catId->getSize()){
  $categoryId= $catId->getFirstItem()->getId();
}
$subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
$subcats = $subcategory->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();

$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');


?>




<div class="offer-tab">
    <ul class="offer-tab-mob">
      <li id="cl-1" class="tab-cl active">Eid Offer</li>
      <li id="cl-2" class="tab-cl">Oled Offer</li>
      <li id="cl-3" class="tab-cl">Mobile Offer</li>
      <li class="arrow"></li>
    </ul>
    <ul class="offer-tab-desktop">
      <?php
        $i = 1;
        foreach ($subcats as $subcat) {
       
       $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
       $_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
        $subcaturl = $subcat->getUrl();
        $_imgHtml = '';
        if($i==1)
        {
          $active = 'tab-cl active';
        }
        else {$active = 'tab-cl';}

      ?>

      <li id="<?php echo 'cl-' . $subcat->getId(); ?>" class="<?php echo $active ;?>" > <?php echo $subcat->getName(); ?>  </li>

      <?php $i++; } ?>

    </ul>


  <?php
        $i = 1;
        foreach ($subcats as $subcat) {
       
       $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
       $_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
        $subcaturl = $subcat->getUrl();
        $_imgHtml = '';
        if($i==1)
        {
          $display = 'display:block';
        }
        else {$display = 'display:none';}


        //get products by category
        
       $categoryId = $subcat->getId();
       $categoryProducts = $block->getCategoryProducts($categoryId);

        $categoryLastProducts=$block->getCategoryLastProducts($categoryId);
       
      
      ?><div id="tabcon-<?php echo $subcat->getId(); ?>" class="offer-tab-con" style="<?php echo $display; ?>">
          <div class="offer-tab-con-desk">
             <div class="left">
          <ul>
            <?php foreach ($categoryProducts as $product) { ?>
             <?php 
            /* echo '<pre>';
             print_r($product->getData()); 
             echo '</pre>';
             //echo "test";
             //exit; */

             //Display Add to cart functions
             $addToCartUrl =  $listBlock->getAddToCartUrl($product);
             ?>
            <li>
              <div class="left-inn">
                <a href="<?= /* @escapeNotVerified */ $product->getProductUrl() ?>">
                  <img src=" <?php echo $imageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getImage(); ?>" alt="#"/>
                 </a>                 
                 <p class="title">
                 <?php 
                    $price = $product->getSaveprice();
                    $formattedPrice = $priceHelper->currency($price, true, false);
                 ?>
                  <?php echo "Save up to" . $formattedPrice;   ?>
                    
                  </p>

                  <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post"> 
                    <?php echo $block->getBlockHtml('formkey')?>
                    <div class="btn">
                        <button type="submit" title="Add to Cart" class="action tocart primary">
                            <span>Buy Now</span>
                        </button>
                    </div>   
                 </form>
              
              </div>
            </li>
           

          
       
     
      
     
     
    



        <?php } // product end ?> 
        </ul>
        </div>
        <!-- right section start -->
        <?php foreach ($categoryLastProducts as $lastproducts){
           $imageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $lastproducts->getImage();
        } ?>
          <div class="right">
          <div class="offer-img">
             <a href="<?= /* @escapeNotVerified */ $product->getProductUrl() ?>">
                 <img src=" <?php echo $imageUrl; ?>" alt="#"/>
              </a>
          </div>

          <p class="offer-con">Eid in July prices available now. Save upto <br/>$3000 on selected signature product.</p>
          <a href="#">learn more</a>
        </div>
        <!-- right end --->


       </div>
     </div>
    
   
     

      <?php $i++; }  // category end ?>




     






    
 



