<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<div class="sections nav-sections">
	    <div class="menu">
			<span>1</span>
			<span>1</span>
			<span>1</span>
		</div>
		<nav class="navbar" data-action="navigation">
		    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
		        <?= /* @escapeNotVerified */ $_menu ?>
		        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
		    </ul>
		</nav>
</div>

	